version: '3.7'
services:
  database:
    image: mysql:5.7.9
    container_name: database
    ports:
      - "3306:3306"
    volumes:
      - "database_data:/var/lib/mysql"
    env_file:
      - db.env
    networks:
      - bookmarking-network
  
  cache:
    image: redis:alpine
    container_name: cache
    ports:
      - "6379:6379"
    networks:
      - bookmarking-network

  social_bookmarking_service:
    build: .
    container_name: social_bookmarking_service
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - social_bookmarking.env
    depends_on:
      database:
        condition: service_started
      cache:
        condition: service_started
    volumes:
      - .:/django_app
    networks:
      - bookmarking-network

volumes: 
    database_data:
      driver: local
    
networks:
  bookmarking-network:
    driver: 
      bridge